[project]
name = "dz-catalog-analysis-sklyar-m26-555"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "UnderXander", email = "sklyar16@yandex.ru" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
dz-catalog-analysis-sklyar-m26-555 = "dz_catalog_analysis_sklyar_m26_555:main"

[build-system]
requires = ["uv_build>=0.12.21,<0.13.0"]
build-backend = "uv_build"
